name: Release to PyPI
on:
  push:
    tags: ["*"]

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/virtualenv
    permissions:
      id-token: write
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Build package
        run: uv build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.11
